-- The WRONG way to Retrieve a New USER_ID

INSERT INTO USERS( FIRST_NAME, LAST_NAME )
    VALUES ( 'Adrian', 'Moreno' );
    SELECT MAX( USER_ID ) FROM USERS AS NEW_ID;
INSERT INTO USERS_2_USER_TYPES ( USER_ID, USER_TYPE_ID )
    VALUES ( NEW_ID, 1 )
