-- The BAD Way, Creating the USERS Table Using char. 

CREATE TABLE USERS(
    USER_ID int IDENTITY(1,1) NOT NULL,
    FIRST_NAME char(50) NOT NULL,
    LAST_NAME char(50) NOT NULL,
    CONSTRAINT PK_USERS_USER_ID PRIMARY KEY CLUSTERED ( USER_ID ASC )
)

