-- Creating the USERS_2_USER_TYPES Table

CREATE TABLE USERS_2_USER_TYPES(
    USER_ID int NOT NULL,
    USER_TYPE_ID int NOT NULL,
    CONSTRAINT PK_USERS_2_USER_TYPES PRIMARY KEY CLUSTERED ( USER_ID ASC, USER_TYPE_ID ASC ));

ALTER TABLE USERS_2_USER_TYPES WITH CHECK
    ADD CONSTRAINT FK_USERS_2_USER_TYPES_USERS FOREIGN KEY(USER_ID)
    REFERENCES USERS (USER_ID);
ALTER TABLE USERS_2_USER_TYPES
    CHECK CONSTRAINT FK_USERS_2_USER_TYPES_USERS;
ALTER TABLE USERS_2_USER_TYPES WITH CHECK
    ADD CONSTRAINT FK_USERS_2_USER_TYPES_USER_TYPES FOREIGN KEY(USER_TYPE_ID)
    REFERENCES USER_TYPES (USER_TYPE_ID);
ALTER TABLE USERS_2_USER_TYPES
    CHECK CONSTRAINT FK_USERS_2_USER_TYPES_USER_TYPES;
