-- Creating an Alternate Association Table, USERS_2_USER_TYPES_V2

CREATE TABLE USERS_2_USER_TYPES_V2(
    USER_ID int NOT NULL,
    USER_TYPE_ID int NOT NULL,);

INSERT INTO USERS_2_USER_TYPES_V2
    ( USER_ID, USER_TYPE_ID )
SELECT USER_ID, USER_TYPE_ID
FROM USERS
ORDER BY
    USER_ID DESC  // Turn the contents upside down;

CREATE INDEX IDX_U2UT2_USER_TYPE_ID ON USERS_2_USER_TYPES_V2 ( USER_TYPE_ID );

